// vim: colorcolumn=80 ts=4 sw=4

#include "demowidget.h"

/* GLOBALS FOR PROPERTIES */

enum property_types
{
	PROP_LABEL = 1,
	N_PROPERTIES
};

static GParamSpec *properties[N_PROPERTIES];

/* GLOBALS FOR SIGNALS */

enum signal_types {
	FOOBAR,
	LAST_SIGNAL
};

static guint signals[LAST_SIGNAL];

/* INTERNAL DECLARATIONS */

/* nb: these are not generated by the macros automatically. */

static void demo_widget_dispose (GObject *object);
static void demo_widget_finalize (GObject *object);

/* GOBJECT DEFINITION */

struct _DemoWidget
{
	GtkWidget parent_instance;

	char *label;
	GtkGesture *gesture;
};

G_DEFINE_TYPE (DemoWidget, demo_widget, GTK_TYPE_WIDGET)


/* PRIVATE INTERNAL FUNCTIONS */

/* Properties - Getters and Setters */

static void
demo_widget_set_property (GObject *object,
		guint property_id,
		const GValue *value,
		GParamSpec *pspec)
{
	DemoWidget *self = DEMO_WIDGET(object);

	switch (property_id)
	{
		case PROP_LABEL:
			demo_widget_set_label (self, g_value_get_string (value));
			break;

		default:
			/* We don't have any other property... */
			G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
			break;
	}
}

static void
demo_widget_get_property (GObject *object,
		guint property_id,
		GValue *value,
		GParamSpec *pspec)
{
	DemoWidget *self = DEMO_WIDGET(object);

	switch (property_id)
	{
		case PROP_LABEL:
			g_value_set_string (value, demo_widget_get_label (self));
			break;

		default:
			/* We don't have any other property... */
			G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
			break;
	}
}

static void
demo_widget_snapshot (GtkWidget *widget, GtkSnapshot *snapshot)
{
	DemoWidget *self = DEMO_WIDGET(widget);

	/* Style/CSS feeder object */
	GtkCssProvider *provider;
	/* Style metadata */
	GtkStyleContext *context;
	/* Raw text-rendering object used with GTK */
	PangoLayout *layout;
	/* Same as a GdkRectangle; struct of ints: { x, y, width, height } */
	GtkAllocation allocation;

	layout = gtk_widget_create_pango_layout (widget, NULL);
	pango_layout_set_text (layout, demo_widget_get_label (self), -1);

	context = gtk_widget_get_style_context (widget);
	gtk_style_context_add_class (context, "view");

	provider = gtk_css_provider_new ();

	gtk_css_provider_load_from_data (provider,
			"* {\n"
			"  border: 5px solid blue;\n"
			"}\n",
			-1);

	gtk_style_context_add_provider (context,
			GTK_STYLE_PROVIDER(provider),
			GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);

	gtk_widget_get_allocation (widget, &allocation);

	/* ------------------------------ */
	/* Draw our background and layout */
	/* ------------------------------ */

	gtk_snapshot_render_background (snapshot, context,
			/* double x, */			allocation.x,
			/* double y, */			allocation.y,
			/* double width, */		allocation.width,
			/* double height */		allocation.height);

	gtk_snapshot_render_layout (snapshot, context,
			/* double x, */			allocation.x,
			/* double y, */			allocation.y,
			layout);
}

/* Callbacks */

static void
gesture_released_cb (GtkGestureClick *gesture,
		int n_press,
		double x,
		double y,
		gpointer user_data)
{
	DemoWidget *self = DEMO_WIDGET(user_data);

	g_debug ("%s: clicked - n_press: %d - x: %f - y: %f",
			__func__, n_press, x, y);
}

/* CONSTRUCTORS AND DESTRUCTORS */

static void
demo_widget_init (DemoWidget *self)
{
	GtkWidget *widget = GTK_WIDGET(self);
	
	gtk_widget_set_name (widget, "demowidget");

	/* Setup gesture */
	self->gesture = gtk_gesture_click_new ();
	g_signal_connect (self->gesture, "released",
			G_CALLBACK(gesture_released_cb), self);
	gtk_widget_add_controller (widget, GTK_EVENT_CONTROLLER(self->gesture));
}

static void
demo_widget_dispose (GObject *object)
{
	DemoWidget *self = DEMO_WIDGET(object);

	/* nb: no need to destroy the GtkEventController (ie Gesture) according
	 * to TFM. */

	/* Final step: Chain up */

	G_OBJECT_CLASS(demo_widget_parent_class)->dispose(object);
}

static void
demo_widget_finalize (GObject *object)
{
	DemoWidget *self = DEMO_WIDGET(object);

	/* Always chain up to the parent class; as with dispose(), finalize() is
	 * autogenerated and thus always guaranteed to exist on the parent's class
	 * virtual function table
	 */
	
	G_OBJECT_CLASS(demo_widget_parent_class)->finalize(object);
}

static void
demo_widget_class_init (DemoWidgetClass *klass)
{
	GObjectClass *object_class = G_OBJECT_CLASS(klass);
	GtkWidgetClass *widget_class = GTK_WIDGET_CLASS(klass);
	GParamFlags default_flags =
		G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS | G_PARAM_EXPLICIT_NOTIFY;

	/* map vfuncs */

	object_class->dispose = demo_widget_dispose;
	object_class->finalize = demo_widget_finalize;
	object_class->set_property = demo_widget_set_property;
	object_class->get_property = demo_widget_get_property;

	widget_class->snapshot = demo_widget_snapshot;

	/* properties */

	properties[PROP_LABEL] = g_param_spec_string ("label",
			"Button label",
			"Textual label for our lovely button",
			/* default: */	"Hello, world!",
			default_flags);

	g_object_class_install_properties (object_class, N_PROPERTIES, properties);

	/* signals */

	signals[FOOBAR] = g_signal_new_class_handler ("foobar",
			G_OBJECT_CLASS_TYPE (object_class),
			G_SIGNAL_RUN_LAST,
		/* no default C function */
			NULL,
		/* defaults for accumulator, marshaller &c. */
			NULL, NULL, NULL,	
		/* No return type or params. */
			G_TYPE_NONE, 0);

	/* layout manager */

	gtk_widget_class_set_layout_manager_type (GTK_WIDGET_CLASS(klass),
			GTK_TYPE_BOX_LAYOUT);
}

/* PUBLIC METHOD DEFINITIONS */

void
demo_widget_set_label (DemoWidget *self, const char *label)
{
	g_clear_pointer (&self->label, g_free);
	self->label = g_strdup (label);

	g_object_notify_by_pspec (G_OBJECT(self), properties[PROP_LABEL]);
}

const char *
demo_widget_get_label (DemoWidget *self)
{
	return self->label;
}

GtkWidget *
demo_widget_new (void)
{
	return g_object_new (DEMO_TYPE_WIDGET, NULL);
}
