// vim: colorcolumn=80 ts=4 sw=4

/* This is an extremely simple annotated .c file that implements a custom
 * widget in gtk4 with gobject. All it does is subclasses GtkWidget and creates
 * a widget which is just a button.
 *
 * Requires: glib >= 2.44, gtk4 >= 4.0.0
 *
 * This is a template for a FINAL (as opposed to DERIVABLE gobject type.
 * Final types are simpler. You do most of the work in the C file and just
 * expose a handful of public methods in the .h file.
 *
 * In other words, as it can't be subclassed further, you don't publicly
 * expose the guts of the object at all and it's just all defined and dealt
 * with using standard GObject/GTK functions.
 */

#include "demowidget.h"

/* GOBJECT DEFINITION */

/* First, create the main struct that has the guts of the object in it.
 * Follow the format of the underscore followed by the CamelCase type
 * name that you created in the header file. The typedef is autogenerated
 * by the macros and is expected to be defined here.
 */

struct _DemoWidget {
  GtkWidget parent_instance;

  gchar *label;
  PangoLayout *layout;
  GdkRectangle layout_rect;
  gboolean label_selected;
  GtkGesture *gesture;
};

/* once the main struct is defined as above, here is the next macro. Make sure
 * this goes in before doing anything else. Order matters.
 *
 * First two arguments to the macro are boilerplate. The last is the standard
 * capitalized TYPE macro of *what you're subclassing.* Lowest you can go is
 * G_TYPE_OBJECT for a raw gobject. In this case we're subclassing
 * GtkWidget, so that type macro is specified below.
 */
G_DEFINE_TYPE(DemoWidget, demo_widget, GTK_TYPE_WIDGET)

// Helper functions for Zig. Since we don't have access to the DemoWidget
// data type in Zig and are using an opaque pointer, we need a way to
// access the internal structure. We do this with getter and setters.
gpointer demo_widget_get_parent_class() { return demo_widget_parent_class; }

char *demo_widget_get_label(DemoWidget *self) { return self->label; }
void demo_widget_set_label(DemoWidget *self, char *label) {
  self->label = label;
}

PangoLayout *demo_widget_get_layout(DemoWidget *self) { return self->layout; }
void demo_widget_set_layout(DemoWidget *self, PangoLayout *layout) {
  self->layout = layout;
}

GdkRectangle demo_widget_get_layout_rect(DemoWidget *self) {
  return self->layout_rect;
}
void demo_widget_set_layout_rect(DemoWidget *self, GdkRectangle layout_rect) {
  self->layout_rect = layout_rect;
}

gboolean demo_widget_get_label_selected(DemoWidget *self) {
  return self->label_selected;
}
void demo_widget_set_label_selected(DemoWidget *self, gboolean label_selected) {
  self->label_selected = label_selected;
}

GtkGesture *demo_widget_get_gesture(DemoWidget *self) { return self->gesture; }
void demo_widget_set_gesture(DemoWidget *self, GtkGesture *gesture) {
  self->gesture = gesture;
}
